from com.android.monkeyrunner import MonkeyRunner, MonkeyDevice  
import time
device = MonkeyRunner.waitForConnection()  
device.touch(10, 10, "DOWN_AND_UP")
time.sleep(0.42)
device.touch(10, 10, "DOWN_AND_UP")
time.sleep(0.13)
device.touch(10, 10, "DOWN_AND_UP")
time.sleep(1.2)
device.touch(10, 10, "down_and_up")
time.sleep(0.55)
device.touch(10, 10, "down_and_up")
time.sleep(1.45)
device.touch(10, 10, "down_and_up")
time.sleep(0.55)
device.touch(10, 10, "down_and_up")
time.sleep(0.55)
device.touch(10, 10, "down_and_up")
